version: '3.8'
services:
  backend:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: unless-stopped
